name: cek_akreditasi
description: Cek akreditasi institusi perguruan tinggi online
version: 1.0.1+2
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  simplehttpconnection: ^1.3.1
  ndialog: ^2.0.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - 'assets/'
